name: publish-crate

on:
  workflow_dispatch:

jobs:
  publish-crate:
    # env only allows main anyways but doesn't hurt...
    if: github.ref == 'refs/heads/main'
    environment: DEPLOY_CRATE
    permissions:
      id-token: write # Required for OIDC token exchange
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: rust-lang/crates-io-auth-action@b7e9a28eded4986ec6b1fa40eeee8f8f165559ec
        id: auth

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo publish
